// velite.config.ts -> rss.ts -> posts.ts 在模块顶层就 import 了 .velite/posts.json，
// 而这些文件正是 velite 自己要生成的。全新检出（如 CI）时 .velite/ 整个目录都不存在，
// velite 会直接构建失败。这里在跑 velite 前补一份空的占位数据做引导，
// velite 随后会用真实内容覆盖它们。
import { existsSync, mkdirSync, writeFileSync } from "node:fs";

const seeds = {
  "index.js": `// This file is generated by Velite

export { default as posts } from './posts.json' with { type: 'json' }
export { default as about } from './about.json' with { type: 'json' }
export { default as memos } from './memos.json' with { type: 'json' }`,
  "index.d.ts": `// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Memo = Collections['memos']['schema']['_output']
export declare const memos: Memo[]`,
  "posts.json": "[]",
  "memos.json": "[]",
  "about.json": "{}",
};

mkdirSync(".velite", { recursive: true });
for (const [file, content] of Object.entries(seeds)) {
  if (!existsSync(`.velite/${file}`)) writeFileSync(`.velite/${file}`, content);
}
